import { Orbit } from "lucide-react";
import type { PacoteQuiz } from "./tipos";

export const ASTRONOMIA: PacoteQuiz = {
  key: "astronomia",
  titulo: "",
  destaque: "Cosmos",
  desc: "Planetas, luas, estrelas e missões espaciais",
  icone: Orbit,
  accent: "accent2",
  perguntas: [
    // ── Múltipla escolha ────────────────────────────────────────────────────
    {
      tipo: "escolha",
      simbolo: "☀️",
      enunciado: "Qual é o planeta mais próximo do Sol?",
      opcoes: ["Mercúrio", "Vênus", "Terra", "Marte"],
      correta: 0,
    },
    {
      tipo: "escolha",
      simbolo: "🔴",
      enunciado: "Qual planeta é conhecido como Planeta Vermelho?",
      opcoes: ["Marte", "Júpiter", "Vênus", "Mercúrio"],
      correta: 0,
      explicacao: "A cor vem do óxido de ferro no solo — literalmente ferrugem.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é o maior planeta do Sistema Solar?",
      opcoes: ["Júpiter", "Saturno", "Netuno", "Urano"],
      correta: 0,
      explicacao: "Júpiter tem mais massa que todos os outros planetas somados — duas vezes e meia.",
    },
    {
      tipo: "escolha",
      simbolo: "🪐",
      enunciado: "Qual planeta tem o sistema de anéis mais visível?",
      opcoes: ["Saturno", "Júpiter", "Urano", "Netuno"],
      correta: 0,
      explicacao: "Os quatro gigantes gasosos têm anéis, mas só os de Saturno são fáceis de ver de longe.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a estrela mais próxima da Terra?",
      opcoes: ["O Sol", "Alfa Centauri", "Sirius", "Proxima Centauri"],
      correta: 0,
      explicacao: "Pegadinha clássica: o Sol é uma estrela, e está a apenas 8 minutos-luz daqui.",
    },
    {
      tipo: "escolha",
      enunciado: "Quantos planetas tem o Sistema Solar?",
      opcoes: ["8", "9", "7", "10"],
      correta: 0,
      explicacao: "Eram 9 até 2006, quando Plutão foi reclassificado como planeta anão.",
    },
    {
      tipo: "escolha",
      enunciado: "Em qual galáxia fica o Sistema Solar?",
      opcoes: ["Via Láctea", "Andrômeda", "Triângulo", "Sombrero"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Quem foi o primeiro ser humano a ir ao espaço?",
      opcoes: ["Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "Buzz Aldrin"],
      correta: 0,
      explicacao: "Em 12 de abril de 1961, a bordo da Vostok 1. A volta na Terra durou 108 minutos.",
    },
    {
      tipo: "escolha",
      enunciado: "Quem foi o primeiro ser humano a pisar na Lua?",
      opcoes: ["Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Yuri Gagarin"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual missão levou o ser humano à Lua pela primeira vez?",
      opcoes: ["Apollo 11", "Apollo 13", "Gemini 4", "Soyuz 1"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual telescópio espacial foi lançado em 1990 e ainda opera?",
      opcoes: ["Hubble", "James Webb", "Kepler", "Spitzer"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual telescópio espacial foi lançado no fim de 2021?",
      opcoes: ["James Webb", "Hubble", "Chandra", "Planck"],
      correta: 0,
      explicacao: "Ele observa em infravermelho e fica a 1,5 milhão de km da Terra — longe demais para conserto.",
    },
    {
      tipo: "escolha",
      simbolo: "🔥",
      enunciado: "Qual é o planeta mais quente do Sistema Solar?",
      opcoes: ["Vênus", "Mercúrio", "Marte", "Júpiter"],
      correta: 0,
      explicacao: "Mercúrio é mais perto do Sol, mas Vênus tem um efeito estufa descontrolado: 460 °C, dia e noite.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual planeta gira praticamente 'deitado', com o eixo tombado?",
      opcoes: ["Urano", "Netuno", "Saturno", "Vênus"],
      correta: 0,
      explicacao: "A inclinação de 98° provavelmente veio de uma colisão gigantesca no passado.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a maior lua do Sistema Solar?",
      opcoes: ["Ganimedes", "Titã", "Europa", "Lua"],
      correta: 0,
      explicacao: "Ganimedes, de Júpiter, é maior que o planeta Mercúrio.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual lua de Saturno tem uma atmosfera densa e lagos de metano?",
      opcoes: ["Titã", "Encélado", "Reia", "Mimas"],
      correta: 0,
    },
    {
      tipo: "escolha",
      simbolo: "🌠",
      enunciado: "O que é, de fato, uma 'estrela cadente'?",
      opcoes: [
        "Um meteoro queimando na atmosfera",
        "Uma estrela caindo do céu",
        "Um satélite reentrando",
        "Um cometa passando perto",
      ],
      correta: 0,
      explicacao: "Quase sempre é um grão de poeira espacial se desintegrando a mais de 50 km de altitude.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual constelação aparece na bandeira do Brasil?",
      opcoes: ["Cruzeiro do Sul", "Órion", "Ursa Maior", "Escorpião"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Quanto tempo a luz do Sol leva para chegar à Terra?",
      opcoes: ["Cerca de 8 minutos", "Instantaneamente", "Cerca de 1 hora", "Cerca de 1 segundo"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual galáxia deve colidir com a Via Láctea no futuro distante?",
      opcoes: ["Andrômeda", "Triângulo", "Grande Nuvem de Magalhães", "Sombrero"],
      correta: 0,
      explicacao: "Daqui a uns 4 bilhões de anos. Ninguém precisa se preocupar.",
    },
    {
      tipo: "escolha",
      enunciado: "O que é um ano-luz?",
      opcoes: [
        "Uma medida de distância",
        "Uma medida de tempo",
        "Uma medida de brilho",
        "Uma medida de massa",
      ],
      correta: 0,
      explicacao: "É a distância que a luz percorre em um ano: cerca de 9,5 trilhões de quilômetros.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual sonda humana já saiu do Sistema Solar?",
      opcoes: ["Voyager 1", "Cassini", "Juno", "New Horizons"],
      correta: 0,
      explicacao: "Lançada em 1977, cruzou a heliopausa em 2012 e ainda envia dados.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual corpo celeste foi rebaixado a planeta anão em 2006?",
      opcoes: ["Plutão", "Ceres", "Éris", "Makemake"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "O que acontece com a luz na borda de um buraco negro?",
      opcoes: [
        "Não consegue escapar depois do horizonte de eventos",
        "Fica presa girando para sempre",
        "É refletida de volta",
        "Muda de cor e escapa",
      ],
      correta: 0,
    },

    {
      tipo: "escolha",
      enunciado: "Em qual planeta fica a maior montanha do Sistema Solar?",
      opcoes: ["Marte", "Vênus", "Júpiter", "Mercúrio"],
      correta: 0,
      explicacao: "O Olympus Mons tem cerca de 22 km de altura — quase três Everestes empilhados.",
    },
    {
      tipo: "escolha",
      enunciado: "O que é a Grande Mancha Vermelha de Júpiter?",
      opcoes: [
        "Uma tempestade que dura séculos",
        "Uma cratera de impacto gigante",
        "Um vulcão em atividade",
        "Um oceano de metano",
      ],
      correta: 0,
      explicacao: "Um furacão que já foi maior que duas Terras — e que vem encolhendo nas últimas décadas.",
    },
    {
      tipo: "escolha",
      enunciado: "Por que uma estrela que vemos no céu pode já não existir mais?",
      opcoes: [
        "A luz dela leva milhares de anos para chegar até nós",
        "Porque o céu é uma projeção da atmosfera",
        "Porque estrelas mudam de lugar constantemente",
        "Porque o telescópio distorce a imagem",
      ],
      correta: 0,
      explicacao: "Olhar para o céu é olhar para o passado: cada ponto de luz mostra a estrela como ela era quando aquela luz partiu.",
    },

    // ── Mito ou Fato ────────────────────────────────────────────────────────
    {
      tipo: "vf",
      afirmacao: "Existe chuva de diamantes em alguns planetas.",
      verdadeiro: true,
      explicacao: "Em Urano e Netuno a pressão comprime o carbono da atmosfera até virar diamante, que afunda como chuva.",
    },
    {
      tipo: "vf",
      afirmacao: "Um dia em Vênus dura mais que um ano em Vênus.",
      verdadeiro: true,
      explicacao: "Vênus leva 243 dias terrestres para girar em torno de si e 225 para dar a volta no Sol.",
    },
    {
      tipo: "vf",
      afirmacao: "Buracos negros sugam tudo que existe ao redor deles, sem parar.",
      verdadeiro: false,
      explicacao: "Fora do horizonte de eventos, a gravidade é igual à de qualquer objeto de mesma massa. Se o Sol virasse um buraco negro, a Terra continuaria orbitando normalmente.",
    },
    {
      tipo: "vf",
      afirmacao: "Não existe som no espaço.",
      verdadeiro: true,
      explicacao: "Som precisa de um meio para se propagar, e o vácuo não tem praticamente nenhuma matéria.",
    },
    {
      tipo: "vf",
      afirmacao: "Astronautas flutuam na Estação Espacial porque lá não existe gravidade.",
      verdadeiro: false,
      explicacao: "A 400 km de altitude a gravidade ainda é quase 90% da que sentimos aqui. Eles flutuam porque a estação está em queda livre permanente — caindo e errando a Terra o tempo todo.",
    },
    {
      tipo: "vf",
      afirmacao: "A Lua está se afastando da Terra alguns centímetros por ano.",
      verdadeiro: true,
      explicacao: "Cerca de 3,8 cm por ano. Os espelhos deixados pelas missões Apollo permitem medir isso a laser.",
    },
    {
      tipo: "vf",
      afirmacao: "A Estrela Polar é a estrela mais brilhante do céu noturno.",
      verdadeiro: false,
      explicacao: "A mais brilhante é Sirius. A Polar é útil por marcar o norte, não por brilhar — nem entra nas cinquenta mais luminosas vistas daqui.",
    },
    {
      tipo: "vf",
      afirmacao: "Saturno flutuaria se existisse uma banheira grande o bastante.",
      verdadeiro: true,
      explicacao: "A densidade média de Saturno é menor que a da água. Ele é quase todo hidrogênio e hélio.",
    },
    {
      tipo: "vf",
      afirmacao: "O lado escuro da Lua nunca recebe luz do Sol.",
      verdadeiro: false,
      explicacao: "O nome engana: é o lado oculto, que nunca é visto da Terra porque a Lua gira em sincronia conosco. Ele pega Sol como qualquer outro.",
    },
    {
      tipo: "vf",
      afirmacao: "O Sol é uma estrela gigante em comparação com as outras da galáxia.",
      verdadeiro: false,
      explicacao: "É uma estrela de porte médio. A maioria das estrelas da Via Láctea é menor e mais fria que ele.",
    },

    // ── Ordenar ─────────────────────────────────────────────────────────────
    {
      tipo: "ordem",
      enunciado: "Coloque os planetas na ordem, do MAIS PRÓXIMO do Sol.",
      dicaOrdem: "mais próximo do Sol primeiro",
      itens: ["Mercúrio", "Vênus", "Terra", "Marte"],
    },
    {
      tipo: "ordem",
      enunciado: "Coloque os gigantes gasosos do MAIOR para o MENOR.",
      dicaOrdem: "maior primeiro",
      itens: ["Júpiter", "Saturno", "Urano", "Netuno"],
      explicacao: "Urano é levemente maior que Netuno em diâmetro, mas Netuno é mais massivo.",
    },
    {
      tipo: "ordem",
      enunciado: "Coloque os marcos da corrida espacial em ordem CRONOLÓGICA.",
      dicaOrdem: "mais antigo primeiro",
      itens: ["Sputnik 1", "Gagarin no espaço", "Apollo 11 na Lua", "Telescópio Hubble"],
      explicacao: "1957 · 1961 · 1969 · 1990.",
    },
    {
      tipo: "ordem",
      enunciado: "Coloque do MAIS QUENTE para o MAIS FRIO.",
      dicaOrdem: "mais quente primeiro",
      itens: ["Vênus", "Mercúrio", "Terra", "Marte"],
      explicacao: "Vênus 460 °C · Mercúrio varia de 430 °C a −180 °C · Terra 15 °C · Marte −60 °C.",
    },

    // ── Pistas ──────────────────────────────────────────────────────────────
    {
      tipo: "pistas",
      pistas: [
        "Sou o segundo planeta a partir do Sol.",
        "Giro no sentido contrário ao da maioria.",
        "Minha atmosfera tem nuvens de ácido sulfúrico e faz 460 °C aqui.",
      ],
      opcoes: ["Vênus", "Mercúrio", "Marte", "Júpiter"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Sou a maior lua do Sistema Solar.",
        "Sou maior que o planeta Mercúrio.",
        "Orbito Júpiter e fui descoberto por Galileu.",
      ],
      opcoes: ["Ganimedes", "Titã", "Calisto", "Europa"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Fui descoberto em 1930.",
        "Perdi meu posto oficial em 2006.",
        "A sonda New Horizons me visitou em 2015.",
      ],
      opcoes: ["Plutão", "Ceres", "Éris", "Netuno"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Sou uma estrela supergigante vermelha.",
        "Meu nome vem do árabe e marco o ombro de um caçador.",
        "Estou na constelação de Órion e posso explodir como supernova.",
      ],
      opcoes: ["Betelgeuse", "Rigel", "Sirius", "Antares"],
      correta: 0,
    },
  ],
};
