import { Globe2 } from "lucide-react";
import type { PacoteQuiz } from "./tipos";

export const GEOGRAFIA: PacoteQuiz = {
  key: "geografia",
  titulo: "Você sabe onde",
  destaque: "fica?",
  desc: "Bandeiras, capitais, rios e recordes do mundo",
  icone: Globe2,
  accent: "success",
  perguntas: [
    // ── Múltipla escolha ────────────────────────────────────────────────────
    {
      tipo: "escolha",
      simbolo: "🇯🇵",
      enunciado: "Qual é a capital do Japão?",
      opcoes: ["Tóquio", "Quioto", "Osaka", "Nagoia"],
      correta: 0,
      explicacao: "Quioto foi a capital até 1868, quando o imperador se mudou para Edo — rebatizada Tóquio.",
    },
    {
      tipo: "escolha",
      simbolo: "🇨🇦",
      enunciado: "De que país é esta bandeira?",
      opcoes: ["Canadá", "Peru", "Áustria", "Dinamarca"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a capital da Austrália?",
      opcoes: ["Camberra", "Sydney", "Melbourne", "Brisbane"],
      correta: 0,
      explicacao: "Camberra foi construída do zero justamente para encerrar a briga entre Sydney e Melbourne.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual destes países NÃO faz fronteira com o Brasil?",
      opcoes: ["Chile", "Peru", "Bolívia", "Colômbia"],
      correta: 0,
      explicacao: "Só Chile e Equador não fazem fronteira com o Brasil na América do Sul.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a moeda do Japão?",
      opcoes: ["Iene", "Won", "Yuan", "Rupia"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual destes países tem o português como idioma oficial?",
      opcoes: ["Angola", "Quênia", "Marrocos", "Senegal"],
      correta: 0,
      explicacao: "São nove países lusófonos, e Angola é o mais populoso da África entre eles.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é o maior país do mundo em área?",
      opcoes: ["Rússia", "Canadá", "China", "Estados Unidos"],
      correta: 0,
      explicacao: "A Rússia sozinha ocupa mais de 11% de toda a terra firme do planeta.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual rio despeja mais água no mar por segundo?",
      opcoes: ["Amazonas", "Nilo", "Yangtzé", "Mississippi"],
      correta: 0,
      explicacao: "O Amazonas sozinho responde por cerca de um quinto de toda a água doce que chega aos oceanos.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é o maior oceano do planeta?",
      opcoes: ["Pacífico", "Atlântico", "Índico", "Ártico"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Em que país fica Machu Picchu?",
      opcoes: ["Peru", "Bolívia", "México", "Equador"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a capital do Canadá?",
      opcoes: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a capital nacional mais alta do mundo?",
      opcoes: ["La Paz", "Quito", "Bogotá", "Cidade do México"],
      correta: 0,
      explicacao: "La Paz fica a mais de 3.600 metros — chegar de avião já dá falta de ar.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual é o menor país do mundo?",
      opcoes: ["Vaticano", "Mônaco", "Nauru", "San Marino"],
      correta: 0,
      explicacao: "O Vaticano tem cerca de 0,44 km² — dá para atravessar a pé em poucos minutos.",
    },
    {
      tipo: "escolha",
      enunciado: "Em que continente fica o Deserto do Saara?",
      opcoes: ["África", "Ásia", "Oceania", "América do Sul"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a capital da Argentina?",
      opcoes: ["Buenos Aires", "Córdoba", "Rosário", "Mendoza"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual país tem o formato parecido com uma bota?",
      opcoes: ["Itália", "Grécia", "Portugal", "Croácia"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual país tem 11 fusos horários dentro do próprio território?",
      opcoes: ["Rússia", "China", "Canadá", "Brasil"],
      correta: 0,
      explicacao: "A China é quase tão larga quanto, mas adota um fuso único para o país inteiro.",
    },
    {
      tipo: "escolha",
      enunciado: "O Estreito de Gibraltar separa a Europa de qual continente?",
      opcoes: ["África", "Ásia", "América", "Oceania"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a capital do Egito?",
      opcoes: ["Cairo", "Alexandria", "Luxor", "Gizé"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Em que cidade fica o Cristo Redentor?",
      opcoes: ["Rio de Janeiro", "Salvador", "São Paulo", "Belo Horizonte"],
      correta: 0,
    },
    {
      tipo: "escolha",
      enunciado: "Qual é a moeda do Reino Unido?",
      opcoes: ["Libra esterlina", "Euro", "Coroa", "Franco"],
      correta: 0,
    },
    {
      tipo: "escolha",
      simbolo: "🗻",
      enunciado: "Qual é a montanha mais alta do mundo?",
      opcoes: ["Everest", "K2", "Aconcágua", "Kilimanjaro"],
      correta: 0,
      explicacao: "8.849 metros, na fronteira entre Nepal e China.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual estado brasileiro tem a maior área?",
      opcoes: ["Amazonas", "Pará", "Mato Grosso", "Minas Gerais"],
      correta: 0,
      explicacao: "O Amazonas é maior que a França, a Espanha e a Alemanha somadas.",
    },
    {
      tipo: "escolha",
      enunciado: "Qual país faz fronteira com o maior número de outros países?",
      opcoes: ["China", "Brasil", "Alemanha", "Índia"],
      correta: 0,
      explicacao: "China e Rússia empatam em 14 vizinhos cada. O Brasil tem 10.",
    },

    {
      tipo: "escolha",
      enunciado: "O Lago Titicaca fica na fronteira entre quais países?",
      opcoes: ["Peru e Bolívia", "Chile e Argentina", "Brasil e Paraguai", "Equador e Colômbia"],
      correta: 0,
      explicacao: "É o maior lago navegável de grande altitude do mundo, a 3.812 metros.",
    },
    {
      tipo: "escolha",
      enunciado: "Com quantos países Portugal faz fronteira terrestre?",
      opcoes: ["Apenas 1", "2", "3", "Nenhum"],
      correta: 0,
      explicacao: "Só com a Espanha — 1.214 km, uma das fronteiras mais antigas ainda em vigor na Europa.",
    },

    // ── Mito ou Fato ────────────────────────────────────────────────────────
    {
      tipo: "vf",
      afirmacao: "A Austrália é ao mesmo tempo um país e um continente.",
      verdadeiro: true,
      explicacao: "É o único caso no mundo — por isso a região toda costuma ser chamada de Oceania.",
    },
    {
      tipo: "vf",
      afirmacao: "O Rio Amazonas nasce no Brasil.",
      verdadeiro: false,
      explicacao: "Ele nasce nos Andes peruanos e só depois entra em território brasileiro.",
    },
    {
      tipo: "vf",
      afirmacao: "A Groenlândia é maior que o Brasil.",
      verdadeiro: false,
      explicacao: "Ela parece gigante nos mapas por causa da projeção de Mercator, mas tem 2,1 milhões de km² contra 8,5 do Brasil.",
    },
    {
      tipo: "vf",
      afirmacao: "Istambul fica em dois continentes ao mesmo tempo.",
      verdadeiro: true,
      explicacao: "O Estreito de Bósforo corta a cidade: um lado é Europa, o outro é Ásia.",
    },
    {
      tipo: "vf",
      afirmacao: "A capital dos Estados Unidos é Nova York.",
      verdadeiro: false,
      explicacao: "É Washington, D.C. Nova York foi capital por pouco tempo, no fim do século XVIII.",
    },
    {
      tipo: "vf",
      afirmacao: "A África do Sul tem uma única capital.",
      verdadeiro: false,
      explicacao: "Tem três: Pretória (executiva), Cidade do Cabo (legislativa) e Bloemfontein (judiciária).",
    },
    {
      tipo: "vf",
      afirmacao: "Medido da base ao topo, o Everest é a montanha mais alta da Terra.",
      verdadeiro: false,
      explicacao: "É o ponto mais alto acima do nível do mar, mas o Mauna Kea, no Havaí, mede mais de 10 km da base submarina ao cume.",
    },
    {
      tipo: "vf",
      afirmacao: "O Deserto do Saara já foi uma região verde, com rios e lagos.",
      verdadeiro: true,
      explicacao: "Há cerca de 6 mil anos era savana. A mudança na órbita da Terra secou tudo.",
    },
    {
      tipo: "vf",
      afirmacao: "A Rússia faz fronteira com a Coreia do Norte.",
      verdadeiro: true,
      explicacao: "Uma fronteira curtíssima, de apenas 17 km, no extremo leste russo.",
    },
    {
      tipo: "vf",
      afirmacao: "O Chile é o país mais comprido do mundo no sentido norte-sul.",
      verdadeiro: true,
      explicacao: "São mais de 4.000 km de extensão — e em alguns pontos menos de 100 km de largura.",
    },

    // ── Ordenar ─────────────────────────────────────────────────────────────
    {
      tipo: "ordem",
      enunciado: "Coloque do MAIOR para o MENOR em área.",
      dicaOrdem: "maior primeiro",
      itens: ["Rússia", "Canadá", "China", "Brasil"],
    },
    {
      tipo: "ordem",
      enunciado: "Coloque do MAIS AO NORTE para o MAIS AO SUL.",
      dicaOrdem: "mais ao norte primeiro",
      itens: ["Noruega", "Espanha", "Marrocos", "África do Sul"],
    },
    {
      tipo: "ordem",
      enunciado: "Coloque as montanhas da MAIS ALTA para a MAIS BAIXA.",
      dicaOrdem: "mais alta primeiro",
      itens: ["Everest", "K2", "Aconcágua", "Kilimanjaro"],
      explicacao: "Everest 8.849 m · K2 8.611 m · Aconcágua 6.961 m · Kilimanjaro 5.895 m.",
    },
    {
      tipo: "ordem",
      enunciado: "Coloque do MAIS POPULOSO para o MENOS POPULOSO.",
      dicaOrdem: "mais populoso primeiro",
      itens: ["Índia", "China", "Estados Unidos", "Indonésia"],
      explicacao: "A Índia ultrapassou a China em 2023 e hoje é o país mais populoso do mundo.",
    },

    // ── Pistas ──────────────────────────────────────────────────────────────
    {
      tipo: "pistas",
      pistas: [
        "Sou o único país que ocupa um continente inteiro.",
        "Meus animais mais famosos andam aos saltos.",
        "Minha maior cidade não é a minha capital.",
      ],
      opcoes: ["Austrália", "Canadá", "Indonésia", "Nova Zelândia"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Sou formado por mais de 17 mil ilhas.",
        "Minha capital fica na ilha de Java.",
        "Tenho a maior população muçulmana do mundo.",
      ],
      opcoes: ["Indonésia", "Filipinas", "Malásia", "Índia"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Fui o berço de uma civilização às margens de um grande rio.",
        "Tenho as pirâmides mais famosas do planeta.",
        "Meu canal liga o Mediterrâneo ao Mar Vermelho.",
      ],
      opcoes: ["Egito", "Iraque", "Sudão", "Turquia"],
      correta: 0,
    },
    {
      tipo: "pistas",
      pistas: [
        "Sou formado por quatro ilhas principais.",
        "Minha montanha mais famosa é um vulcão adormecido.",
        "Minha moeda é o iene.",
      ],
      opcoes: ["Japão", "Filipinas", "Coreia do Sul", "Nova Zelândia"],
      correta: 0,
    },
  ],
};
